PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX ofo: <http://obofoundry.github.io/vocabulary/>

SELECT DISTINCT ?ontology {
    ?x  ofo:activity_status  "active" ;
        dcat:accessURL ?ontology .
}