name: Update OBO Ontology Version
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run
      run: ./gradlew run --args="output.csv"

    - name: Archive output file
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
           output.csv