name: Update OBO Ontology Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
      with:
        gradle-home-cache-cleanup: true

    - name: Run
      run: mkdir -p web && ./gradlew run --args="extract -o web/output.ttl" && ./gradlew run --args="transform -i web/output.ttl -o web/output.html" && ./gradlew run --args="transform -i web/output.ttl -o web/output.csv"

    - name: Archive output file
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: |
           web/output.ttl
           web/output.csv
           web/output.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web
